# Generated by Django 5.2 on 2025-04-09 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subastas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puja',
            name='pujador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to=settings.AUTH_USER_MODEL),
        ),
    ]
