# Generated by Django 5.2 on 2025-05-09 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0002_subasta_usuario_alter_puja_pujador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='valoracion',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0, message='La valoración debe ser al menos 1.0'), django.core.validators.MaxValueValidator(5.0, message='La valoración no puede ser mayor a 5.0')]),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La valoración mínima es 1'), django.core.validators.MaxValueValidator(5, message='La valoración máxima es 5')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='subastas.subasta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_actualizacion',),
                'unique_together': {('usuario', 'subasta')},
            },
        ),
    ]
