# Generated by Django 5.2 on 2025-05-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0004_comentario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='subastas_rating',
        ),
    ]
